apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-snapshots
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-snapshots
    spec:
      containers:
      - name: k8s-snapshots
        image: elsdoerfer/k8s-snapshots:v2.0
        env:
          - name: USE_CLAIM_NAME
            value: "true"
          - name: GCLOUD_JSON_KEYFILE_STRING
            valueFrom:
              secretKeyRef:
                name: compute-snapshot-key
                key: key.json
